### ISSUE TITLE
11월 13일 ~ 11월 20일

### ISSUE THREAD

**Issue by SkyLightQP** [Sustagram/conference-note#12]
11월 13일 ~ 11월 20일

-------

**영상 내용**

- 팀원소개
- 개발 동기
- 필요성
- 기능
- 장점
- 개선점
- 발전 계획

**Comment by SkyLightQP** [comment]
- `multipart/form-data`를 통해 이미지 업로드 가능
- S3하고 연동
- 파일 올리면 해당 S3 링크 보내주기

**Comment by SkyLightQP** [comment]
https://medium.com/@_diana_lee/react-infinite-scroll-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0-fbd51a8a099f

**Comment by SkyLightQP** [comment]
**TODO**
- [ ] 좋아요 기능 (프)
- [x] 좋아요 기능 (백)
- [ ] 댓글 기능 (프)
- [x] 댓글 기능 (백)
- [ ] 마이페이지 뷰 구현 (프)
- [x] 유저ID(이메일)로 정보 가져오는 API (백)
- [ ] 팔로워 목록에서 애들 누르면 이동 (프)
- [x] 내 기준으로 팔로워 불러오는 API (백)

**Comment by arkc1009** [comment]
- 팔로워 리스트 뷰
- 업로드 프론즈 PR
- 프로필 사진 atomic화

**Comment by arkc1009** [comment]
> **TODO**
> 
> * [ ]  좋아요 기능 (프, 백)
> * [ ]  댓글 기능 (프)
> * [ ]  마이페이지 뷰 구현 (프)
> * [ ]  유저ID(이메일)로 정보 가져오는 API (백)
> * [ ]  팔로워 목록에서 애들 누르면 이동 (프)
> * [ ]  내 기준으로 팔로워 불러오는 API (백)
