### ISSUE TITLE
11월 20일 ~ 11월 27일

### ISSUE THREAD

**Issue by SkyLightQP** [Sustagram/conference-note#13]
11월 20일 ~ 11월 27일

**Comment by SkyLightQP** [comment]
- 썸네일 제작 필요

**Comment by SkyLightQP** [comment]
### 주요 목표
- 백엔드 API하고 프론트엔드 연결

**TODO**
- [x] 좋아요 기능 (프)
- [x] 댓글 기능 (프)
- [ ] 마이페이지 뷰 구현 (프)
- [ ] 팔로워 목록에서 애들 누르면 이동 (프)
- [ ] 무한스크롤

**Comment by SkyLightQP** [comment]
- 댓글, 좋아요, 팔로우, 유저 관련 API 제작 완료

**Comment by SkyLightQP** [comment]
- AWS S3 작업 중

**Comment by SkyLightQP** [comment]
- Swagger로 API 문서 작업 완료

**Comment by arkc1009** [comment]
- 좋아요 여부에 따른 아이콘 변경
- 좋아요 백과 연동 틀잡기
- 팔로워리스트 백 연동 했다가 브랜치를 잘못 선택해서 다시 할 예정

 **My Todo**
- [x] 좋아요 애니메이션 구현
- [x] 좋아요 백과 연동
- [ ] 팔로워리스트 백과 연동

**Comment by SkyLightQP** [comment]
좋아요 기능 작동안하는 이슈 해결

**Comment by SkyLightQP** [comment]
**TODO**
- [ ] 좋아요, 팔로우 상태를 삭제가 아닌 status 필드로 변경

**Comment by SkyLightQP** [comment]
- 글, 사진 업로드 기능 완성
- 기본 프로필 사진 변경
- 로고 텍스트를 인스타그램과 비슷한 폰트로 변경

**Comment by SkyLightQP** [comment]
- 댓글 기능 완료

**Comment by SkyLightQP** [comment]
- 좋아요 개수 가져오는 기능 완료
